# Generated by Django 4.2 on 2023-05-04 16:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ("uuid",)},
        ),
        migrations.RenameField(
            model_name="user",
            old_name="id",
            new_name="uuid",
        ),
    ]
