# Generated by Django 4.2 on 2023-05-04 16:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_options_rename_id_user_uuid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ("id",)},
        ),
        migrations.RenameField(
            model_name="user",
            old_name="uuid",
            new_name="id",
        ),
    ]
