# Generated by Django 4.2 on 2023-05-04 12:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("genres", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=200)),
                ("synopsis", models.TextField()),
                ("published_date", models.DateField()),
                ("publishing_company", models.CharField(max_length=200)),
                ("language", models.CharField(max_length=200)),
                ("quantity", models.IntegerField()),
                (
                    "genres",
                    models.ManyToManyField(related_name="books", to="genres.genre"),
                ),
            ],
        ),
    ]
