# Generated by Django 4.2 on 2023-05-04 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user_following", "0001_initial"),
        ("books", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="user_following",
            field=models.ManyToManyField(
                related_name="books",
                through="user_following.UserFollowing",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
