# Generated by Django 4.2 on 2023-05-04 12:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("book_copy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookLoan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("loan_date", models.DateTimeField(auto_now_add=True)),
                ("max_return_date", models.DateTimeField(blank=True)),
                ("returned_date", models.DateTimeField(blank=True, null=True)),
                (
                    "book_copy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_loan",
                        to="book_copy.bookcopy",
                    ),
                ),
            ],
        ),
    ]
