# Generated by Django 4.2 on 2023-05-04 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("book_copy", "0001_initial"),
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookcopy",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="books.book"
            ),
        ),
    ]
