# Generated by Django 4.2 on 2023-05-04 21:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("book_loan", "0002_initial"),
        ("book_copy", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookcopy",
            name="book_loans",
            field=models.ManyToManyField(
                related_name="book_copy",
                through="book_loan.BookLoan",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bookcopy",
            name="lending_time_limit",
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
